import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { createTestHarness, parseToolResult } from '@chrischall/mcp-utils/test';
import { ZolaClient } from '../src/client.js';
import { registerHealthcheckTools } from '../src/tools/healthcheck.js';

/**
 * A CloudFront WAF block is not a rejected credential (mcp-host#1015).
 *
 * Observed 2026-10-01 from a hosted Zola: `GET /v4/your-wedding` answered 403
 * in 35 ms with CloudFront's own HTML "Request blocked" page while the same
 * account worked in a browser, and `zola_healthcheck` reported
 * `credential_rejected` and told the user to re-sign in. The edge refused the
 * request before the API ever saw the token.
 *
 * These run the REAL client against the page CloudFront serves, so they fail
 * if anything between the response and the healthcheck — truncation, redaction,
 * the auth retry — drops the markers the shared classifier reads.
 */

// CloudFront's block page, as served (whitespace trimmed, ids made up).
const CLOUDFRONT_BLOCK =
  '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">' +
  '<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">' +
  '<TITLE>ERROR: The request could not be satisfied</TITLE></HEAD><BODY>' +
  '<H1>403 ERROR</H1><H2>The request could not be satisfied.</H2><HR noshade size="1px">' +
  'Request blocked. We can\'t connect to the server for this app or website at this time. ' +
  'There might be too much traffic or a configuration error. Try again later, or contact the app or ' +
  'website owner.<BR clear="all">If you provide content to customers through CloudFront, you can find ' +
  'steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.' +
  '<BR clear="all"><HR noshade size="1px"><PRE>Generated by cloudfront (CloudFront)\n' +
  'Request ID: AbCdEfGhIjKlMnOpQrStUvWxYz0123456789abcdefghijklmnopqr==</PRE><ADDRESS></ADDRESS></BODY></HTML>';

function makeMockJwt(exp: number): string {
  const header = Buffer.from(JSON.stringify({ alg: 'HS256', typ: 'JWT' })).toString('base64url');
  const payload = Buffer.from(
    JSON.stringify({ exp, iss: 'svc-user', sub: 'test-user', session_id: 'test-session-id' }),
  ).toString('base64url');
  return `${header}.${payload}.mock-signature`;
}

const FUTURE_EXP = Math.floor(Date.now() / 1000) + 3600;

function blocked(): Response {
  const headers = new Headers({
    'content-type': 'text/html',
    'x-cache': 'Error from cloudfront',
    server: 'CloudFront',
  });
  return {
    ok: false,
    status: 403,
    statusText: 'Forbidden',
    headers,
    text: async () => CLOUDFRONT_BLOCK,
  } as unknown as Response;
}

interface Result {
  ok: boolean;
  error?: { kind: string; message: string };
  hint: string;
}

async function healthcheck(client: ZolaClient): Promise<Result> {
  const h = await createTestHarness((server) => registerHealthcheckTools(server, client));
  const res = await h.client.callTool({ name: 'zola_healthcheck', arguments: {} });
  await h.close?.();
  return parseToolResult<Result>(res as never);
}

describe('a CloudFront block reads as edge_blocked, not a rejected credential', () => {
  let fetchMock: ReturnType<typeof vi.fn>;

  beforeEach(() => {
    fetchMock = vi.fn();
    vi.stubGlobal('fetch', fetchMock);
    process.env.ZOLA_REFRESH_TOKEN = makeMockJwt(FUTURE_EXP);
    delete process.env.ZOLA_SESSION_TOKEN;
    process.env.ZOLA_DISABLE_FETCHPROXY = '1';
  });

  afterEach(() => {
    vi.restoreAllMocks();
    vi.unstubAllGlobals();
    delete process.env.ZOLA_REFRESH_TOKEN;
    delete process.env.ZOLA_SESSION_TOKEN;
    delete process.env.ZOLA_DISABLE_FETCHPROXY;
  });

  it('on the probe itself — the 2026-10-01 shape, with a valid session token', async () => {
    process.env.ZOLA_SESSION_TOKEN = makeMockJwt(FUTURE_EXP);
    fetchMock.mockResolvedValue(blocked());

    const r = await healthcheck(new ZolaClient());

    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
    // The copy that sent the user to re-sign in must not be what they read.
    expect(r.hint).not.toMatch(/rejected the refresh token/);
  });

  it('on the session refresh the probe triggers', async () => {
    // No session token, so the probe first mints one — and CloudFront blocks
    // the mint. Same edge, same page, one call earlier.
    fetchMock.mockResolvedValue(blocked());

    const r = await healthcheck(new ZolaClient());

    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
    expect(r.hint).not.toMatch(/rejected the refresh token/);
  });

  it('control: a 401 with Zola\'s JSON error is still a rejected credential', async () => {
    process.env.ZOLA_SESSION_TOKEN = makeMockJwt(FUTURE_EXP);
    fetchMock.mockResolvedValue({
      ok: false,
      status: 401,
      statusText: 'Unauthorized',
      headers: new Headers({ 'content-type': 'application/json' }),
      text: async () => JSON.stringify({ error: 'invalid token' }),
    } as unknown as Response);

    const r = await healthcheck(new ZolaClient());

    expect(r.error?.kind).toBe('credential_rejected');
  });
});
